version: "3.8"

services:
  traefik:
    build:
      context: ./traefik
    container_name: xpory-local-proxy
    ports:
      - "443:443"
    volumes:
      - ./traefik/certs:/certs:ro
      - ./tls:/tls:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
