version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: xpory-cp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-xpory_cp}
      POSTGRES_USER: ${DB_USERNAME:-xpory_cp}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-supersecret}
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  controlplane:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-xpory_cp}
      DB_USERNAME: ${DB_USERNAME:-xpory_cp}
      DB_PASSWORD: ${DB_PASSWORD:-supersecret}
      SERVER_SSL_ENABLED: "false"
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY:-}
    ports:
      - "8080:8080"
    restart: unless-stopped
